# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "53b3349f658a984d34a17c22ac334e19"
name = "ankit kumar dev app"
application_url = "https://transcription-stored-predict-netscape.trycloudflare.com"
embedded = true
handle = "ankit-kumar-dev-app"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2023-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_locations,read_orders,read_products,write_assigned_fulfillment_orders,write_customers,write_fulfillments,write_orders"

[auth]
redirect_urls = [
  "https://transcription-stored-predict-netscape.trycloudflare.com/auth/callback",
  "https://transcription-stored-predict-netscape.trycloudflare.com/auth/shopify/callback",
  "https://transcription-stored-predict-netscape.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://transcription-stored-predict-netscape.trycloudflare.com/api/meroxio-proxyyy"
subpath = "meroxio-proxyyy"
prefix = "apps"

[pos]
embedded = false
