# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfb95502aa8f4f718b14d09136fef838"
application_url = "https://ash-instrument-tribe-victorian.trycloudflare.com"
embedded = true
name = "Staging"
handle = "staging-76"

[webhooks]
api_version = "2022-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_draft_orders,write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://ash-instrument-tribe-victorian.trycloudflare.com/auth/callback",
  "https://ash-instrument-tribe-victorian.trycloudflare.com/auth/shopify/callback",
  "https://ash-instrument-tribe-victorian.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://ash-instrument-tribe-victorian.trycloudflare.com/api/floating-cart"
subpath = "floating-cart"
prefix = "apps"

[pos]
embedded = false

[build]
dev_store_url = "shivam-development-store.myshopify.com"
automatically_update_urls_on_dev = true
