# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "72954801cdfa62338163e48bbaf601d0"
application_url = "https://app8.meroxioapps.com/"
embedded = true
name = "MeroxIO Floating Cart Button"
handle = "meroxio-floating-cart-button"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [
  "https://app8.meroxioapps.com/auth/callback",
  "https://app8.meroxioapps.com/auth/shopify/callback",
  "https://app8.meroxioapps.com/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
